import {React} from 'react';
import { ListGroup, ListGroupItem } from 'reactstrap';
import './ListBairros.css';

const json = [{
    "0": {
       "data": "01/01/2021",
       "hora": "19:44:00",
       "natureza_acidente": "COM VÍTIMA",
       "situacao": "FINALIZADA",
       "bairro": "MADALENA",
       "endereco": "RUA BENFICA",
       "detalhe_endereco_acidente": "",
       "complemento": "EM FRENTE AO EXTRA NA SAIDA",
       "bairro_cruzamento": "MADALENA",
       "num_semaforo": "",
       "sentido_via": "SUBURBIO",
       "tipo": "COLISÃO FRONTAL",
       "auto": 1,
       "moto": 1,
       "ciclom": 0,
       "ciclista": 0,
       "pedestre": 0,
       "onibus": 0,
       "caminhao": 0,
       "viatura": 0,
       "outros": 0,
       "vitimas": 1,
       "vitimasfatais": 0,
       "acidente_verificado": "Longo da via",
       "tempo_clima": "Bom",
       "situacao_semaforo": "Não existe",
       "sinalizacao": "Perfeito estado",
       "condicao_via": "Seca",
       "conservacao_via": "Perfeito estado",
       "ponto_controle": "Outros",
       "situacao_placa": "Não há placas",
       "velocidade_max_via": "",
       "mao_direcao": "Dupla",
       "divisao_via1": "Faixa contínua",
       "divisao_via2": "Faixa seccionada",
       "divisao_via3": ""
    },
    "1": {
       "data": "01/01/2021",
       "hora": "23:15:40",
       "natureza_acidente": "COM VÍTIMA",
       "situacao": "FINALIZADA",
       "bairro": "VÁRZEA",
       "endereco": "AV CAXANGA",
       "detalhe_endereco_acidente": "RUA GASTAO VIDIGAL",
       "complemento": "EM FRENTE A UPA DA CAXANGA",
       "bairro_cruzamento": "VÁRZEA",
       "num_semaforo": "281",
       "sentido_via": "CIDADE",
       "tipo": "COLISÃO TRASEIRA",
       "auto": 2,
       "moto": 0,
       "ciclom": 0,
       "ciclista": 0,
       "pedestre": 0,
       "onibus": 0,
       "caminhao": 0,
       "viatura": 0,
       "outros": 0,
       "vitimas": 1,
       "vitimasfatais": 0,
       "acidente_verificado": "Cruzamento",
       "tempo_clima": "Bom",
       "situacao_semaforo": "Sem defeito",
       "sinalizacao": "Perfeito estado",
       "condicao_via": "Oleosa",
       "conservacao_via": "Perfeito estado",
       "ponto_controle": "Outros",
       "situacao_placa": "Outras",
       "velocidade_max_via": "",
       "mao_direcao": "Única",
       "divisao_via1": "Não existe",
       "divisao_via2": "",
       "divisao_via3": ""
    },
    "2": {
       "data": "02/01/2021",
       "hora": "10:54:00",
       "natureza_acidente": "COM VÍTIMA",
       "situacao": "FINALIZADA",
       "bairro": "VASCO DA GAMA",
       "endereco": "RUA RESPLENDOR",
       "detalhe_endereco_acidente": "",
       "complemento": "AO  LADO  DO  COLEGIO ADERBAL  GALVÃO  EM  FRENTE  AO  CONJUNTO RESIDENCIAL  ADERBAL  GALVÃO",
       "bairro_cruzamento": "VASCO DA GAMA",
       "num_semaforo": "",
       "sentido_via": "",
       "tipo": "COLISÃO COM CICLISTA",
       "auto": 1,
       "moto": 1,
       "ciclom": 0,
       "ciclista": 1,
       "pedestre": 0,
       "onibus": 0,
       "caminhao": 0,
       "viatura": 0,
       "outros": 0,
       "vitimas": 1,
       "vitimasfatais": 0,
       "acidente_verificado": "Longo da via",
       "tempo_clima": "Bom",
       "situacao_semaforo": "Não existe",
       "sinalizacao": "Incompleta",
       "condicao_via": "Seca",
       "conservacao_via": "Perfeito estado",
       "ponto_controle": "Não existe",
       "situacao_placa": "Não há placas",
       "velocidade_max_via": "",
       "mao_direcao": "Dupla",
       "divisao_via1": "Não existe",
       "divisao_via2": "",
       "divisao_via3": ""
    },
    "3": {
       "data": "02/01/2021",
       "hora": "11:13:00",
       "natureza_acidente": "COM VÍTIMA",
       "situacao": "FINALIZADA",
       "bairro": "BOA VIAGEM",
       "endereco": "RUA VISCONDE DE JEQUITINHONHA",
       "detalhe_endereco_acidente": "RUA CAPITAO ZUZINHA",
       "complemento": "RUA CAPITÃO ZUZINHA",
       "bairro_cruzamento": "BOA VIAGEM",
       "num_semaforo": "",
       "sentido_via": "SUBURBIO",
       "tipo": "COLISÃO LATERAL",
       "auto": 1,
       "moto": 1,
       "ciclom": 0,
       "ciclista": 0,
       "pedestre": 0,
       "onibus": 0,
       "caminhao": 0,
       "viatura": 0,
       "outros": 0,
       "vitimas": 1,
       "vitimasfatais": 0,
       "acidente_verificado": "Longo da via",
       "tempo_clima": "Bom",
       "situacao_semaforo": "Sem defeito",
       "sinalizacao": "Perfeito estado",
       "condicao_via": "Seca",
       "conservacao_via": "Perfeito estado",
       "ponto_controle": "Faixa de pedestre",
       "situacao_placa": "Outras",
       "velocidade_max_via": "",
       "mao_direcao": "Única",
       "divisao_via1": "Canal",
       "divisao_via2": "",
       "divisao_via3": ""
    },
    "4": {
       "data": "03/01/2021",
       "hora": "09:32:00",
       "natureza_acidente": "COM VÍTIMA",
       "situacao": "FINALIZADA",
       "bairro": "ILHA DO RETIRO",
       "endereco": "AV ENGENHEIRO ABDIAS DE CARVALHO",
       "detalhe_endereco_acidente": "",
       "complemento": "EM FRENTE A LANCHONETE COXINHAS DE BATATA",
       "bairro_cruzamento": "ILHA DO RETIRO",
       "num_semaforo": "",
       "sentido_via": "",
       "tipo": "COLISÃO LATERAL",
       "auto": 1,
       "moto": 1,
       "ciclom": 0,
       "ciclista": 0,
       "pedestre": 0,
       "onibus": 0,
       "caminhao": 0,
       "viatura": 0,
       "outros": 0,
       "vitimas": 2,
       "vitimasfatais": 0,
       "acidente_verificado": "Longo da via",
       "tempo_clima": "Bom",
       "situacao_semaforo": "Sem defeito",
       "sinalizacao": "Perfeito estado",
       "condicao_via": "Seca",
       "conservacao_via": "Perfeito estado",
       "ponto_controle": "Faixa de pedestre",
       "situacao_placa": "Outras",
       "velocidade_max_via": "60 km/h",
       "mao_direcao": "Dupla",
       "divisao_via1": "Faixa contínua",
       "divisao_via2": "Faixa seccionada",
       "divisao_via3": "Canteiro central"
    },
    "5": {
       "data": "03/01/2021",
       "hora": "11:07:00",
       "natureza_acidente": "SEM VÍTIMA",
       "situacao": "FINALIZADA",
       "bairro": "CASA AMARELA",
       "endereco": "RUA OSCAR DE BARROS",
       "detalhe_endereco_acidente": "",
       "complemento": "POSTO DE SAÚDE PROFESSOR MARIO RAMOS",
       "bairro_cruzamento": "CASA AMARELA",
       "num_semaforo": "",
       "sentido_via": "SUBURBIO",
       "tipo": "CHOQUE",
       "auto": 1,
       "moto": 0,
       "ciclom": 0,
       "ciclista": 0,
       "pedestre": 0,
       "onibus": 0,
       "caminhao": 0,
       "viatura": 0,
       "outros": 0,
       "vitimas": 0,
       "vitimasfatais": 0,
       "acidente_verificado": "Longo da via",
       "tempo_clima": "Bom",
       "situacao_semaforo": "Não existe",
       "sinalizacao": "Perfeito estado",
       "condicao_via": "Seca",
       "conservacao_via": "Perfeito estado",
       "ponto_controle": "Não existe",
       "situacao_placa": "R-6a",
       "velocidade_max_via": "",
       "mao_direcao": "Única",
       "divisao_via1": "Não existe",
       "divisao_via2": "",
       "divisao_via3": ""
    }}]

const ListBairros = (props) => {
    return (
        <ListGroup className = 'listgroup container-fluid'>
            <ListGroupItem action id='bairro' href = '#' tag='a'>{json[0]['0'].bairro} - {json[0]['0'].vitimas} VÍTIMAS</ListGroupItem>
            <ListGroupItem action id='bairro' href = '#' tag='a'>{json[0]['1'].bairro} - {json[0]['1'].vitimas} VÍTIMAS</ListGroupItem>
            <ListGroupItem action id='bairro' href = '#' tag='a'>{json[0]['2'].bairro} - {json[0]['2'].vitimas} VÍTIMAS</ListGroupItem>
            <ListGroupItem action id='bairro' href = '#' tag='a'>{json[0]['3'].bairro} - {json[0]['3'].vitimas} VÍTIMAS</ListGroupItem>
            <ListGroupItem action id='bairro' href = '#' tag='a'>{json[0]['4'].bairro} - {json[0]['4'].vitimas} VÍTIMAS</ListGroupItem>
        </ListGroup>
    )
}

export default ListBairros